apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-k8s
        image: user-management-image:1
        imagePullPolicy: Never
        ports:
        - containerPort: 51000
        volumeMounts:
        - mountPath: /app/application.properties
          name: user-config
          subPath: application.properties
      volumes:
      - name: user-config
        configMap:
          name: user-config
          items:
          - key: application.properties
            path: application.properties

