apiVersion: v1
kind: Service
metadata:
  name: order-mysql
spec:
  type: LoadBalancer
  selector:
    app: order-mysql
  ports:
    - port: 30001
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mysql
spec:
  selector:
    matchLabels:
      app: order-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: order-mysql
    spec:
      containers:
        - name: order-mysql
          image: mysql:8
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: orders
          volumeMounts:
            - name: order-mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: order-mysql-initdb
          configMap:
            name: order-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-initdb-config
data:
  initdb.sql: |
    CREATE TABLE orders
    (
        id         VARCHAR(36) NOT null,
        userid     int(36)     NOT null,
        username   VARCHAR(36) NOT NULL,
        roomid     VARCHAR(36) NOT NULL,
        term       int     NOT NULL,
        sum        double     NOT NULL,
        datetime   DATETIME  NOT NULL,
        status     int (36)    NOT NULL,
        PRIMARY KEY (id)
    );
