apiVersion: v1
kind: Service
metadata:
  name: room-mysql
spec:
  type: LoadBalancer
  selector:
    app: room-mysql
  ports:
    - port: 30000
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-mysql
spec:
  selector:
    matchLabels:
      app: room-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: room-mysql
    spec:
      containers:
        - name: room-mysql
          image: mysql:8
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: rooms
          volumeMounts:
            - name: room-mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: room-mysql-initdb
          configMap:
            name: room-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: room-initdb-config
data:
  initdb.sql: |
    CREATE TABLE rooms
    (
        id         VARCHAR(36) not null,
        room       VARCHAR(50) not null,
        detail     VARCHAR(50) not null,
        price      double not null,
        status     int not null,
        deadline   DATETIME not null,
        deadlinereserve   DATETIME not null,
        PRIMARY KEY (id)
    );
