apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user/image:1
          imagePullPolicy: Never
          args: ["--spring.config.location=application.properties"]
          ports:
            - containerPort: 52000
          volumeMounts:
            - mountPath: /app/application.properties
              name: user-config
              subPath: application.properties
      volumes:
        - name: user-config
          configMap:
            name: user-config
            items:
              - key: application.properties
                path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: LoadBalancer
  ports:
    - port: 52001
      targetPort: 52000
  selector:
    app: user
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://user-mysql:30002/users
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.database=MYSQL
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    server.port=52000
