server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 9090

logging:
  level: INFO
  loggers:
    se.citerus: DEBUG

  appenders:
    - type: console
