apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl-envoy
  namespace: bitloops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bl-envoy
  template:
    metadata:
      labels:
        app: bl-envoy
    spec:
      containers:
      - name: envoy
        context: ../envoy
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
