apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl-prometheus
  namespace: bitloops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bl-prometheus
  template:
    metadata:
      labels:
        app: bl-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: bl-prometheus-config
          mountPath: /etc/prometheus
        - name: bl-prometheus-data
          mountPath: /prometheus
      volumes:
      - name: bl-prometheus-config
        configMap:
          name: cm-prometheus-config
      - name: bl-prometheus-data
        persistentVolumeClaim:
          claimName: pvc-bl-prometheus-data

