apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl-jaeger
  namespace: bitloops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bl-jaeger
  template:
    metadata:
      labels:
        app: bl-jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: LOG_LEVEL
          value: debug
        ports:
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 14250
        - containerPort: 14268
        - containerPort: 14269
        - containerPort: 9411