apiVersion: v1
kind: Service
metadata:
  name: bl-mongo
  namespace: bitloops
spec:
  selector:
    app: bl-mongo
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
  type: LoadBalancer