apiVersion: v1
kind: Service
metadata:
  name: bl-jaeger
  namespace: bitloops
spec:
  selector:
    app: bl-jaeger
  ports:
    - protocol: TCP
      port: 6831
      targetPort: 6831
    - protocol: TCP
      port: 6832
      targetPort: 6832
    - protocol: TCP
      port: 5778
      targetPort: 5778
    - protocol: TCP
      port: 16686
      targetPort: 16686
    - protocol: TCP
      port: 4317
      targetPort: 4317
    - protocol: TCP
      port: 4318
      targetPort: 4318
    - protocol: TCP
      port: 14250
      targetPort: 14250
    - protocol: TCP
      port: 14268
      targetPort: 14268
    - protocol: TCP
      port: 14269
      targetPort: 14269
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: LoadBalancer