apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: bitloops
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer