apiVersion: v1
kind: Service
metadata:
  name: bl-postgres
  namespace: bitloops
spec:
  selector:
    app: bl-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer