apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: bitloops
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer