apiVersion: v1
kind: Service
metadata:
  name: bl-envoy
  namespace: bitloops
spec:
  selector:
    app: bl-envoy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer