apiVersion: v1
kind: Service
metadata:
  name: bl-prometheus
  namespace: bitloops
spec:
  selector:
    app: bl-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer