{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "msjc-be.serviceAccountName" . }}
  labels:
  {{ include "msjc-be.labels" . | nindent 4 }}
{{- end -}}
