apiVersion: v1
kind: Service
metadata:
  name: user-mysql
spec:
  type: LoadBalancer
  selector:
    app: user-mysql
  ports:
    - port: 30002
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mysql
spec:
  selector:
    matchLabels:
      app: user-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: user-mysql
    spec:
      containers:
        - name: user-mysql
          image: mysql:8
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'root'
            - name: MYSQL_DATABASE
              value: users
          volumeMounts:
            - name: user-mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: user-mysql-initdb
          configMap:
            name: user-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-initdb-config
data:
  initdb.sql: |
    CREATE TABLE users
    (
        id          int(4) NOT NULL auto_increment,
        password    VARCHAR(36) not null,
        name        VARCHAR(50) not null,
        phone       VARCHAR(50) not null,
        address     VARCHAR(50) not null,
        PRIMARY KEY (id)
    );
